
modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/N0edL/istyping"
license="https://github.com/N0edL/istyping/blob/master/LICENSE.md"

[[mods]]
modId="istyping"
displayName="Is Typing"
version="1.1.0"
logoFile= "pack.png"
authors="NoedL, itskillerluc"
description="This mod adds a feature to the chat that shows when someone is typing."

[[dependencies.istyping]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"